[theme]
base = "dark"
primaryColor = "#a17454"                # Caramel accent
backgroundColor = "#2a2a2a"             # Ink-like, neutral backdrop
secondaryBackgroundColor = "#3a3a3a"    # Contrasting darker panels
textColor = "#f5f2ec"                   # Light cream text
font = "serif"
